# Generated by Django 4.0.4 on 2022-11-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(error_messages={'unique': 'A user with that login already exists.'}, max_length=32, unique=True, verbose_name='login'),
        ),
    ]
